name: publish-lib

on:
  push:
    branches: [lib]
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js environment
        uses: actions/setup-node@v1.4.3
        with:
          # Version Spec of the version to use.  Examples: 10.x, 10.15.1, >=10.15.0
          node-version: 12.x
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Publish lib
        run: |
          git config --global user.name 'CSIDE-Shell'
          git config --global user.email '32689095+CSIDE-Shell@users.noreply.github.com'

          git checkout lib --
          npm install .
          npm run release
          git update-index --refresh || true
          if ! git diff-index --quiet HEAD --; then git add release && git commit -m "Automatic build triggered by $GITHUB_SHA" && git push origin lib; fi
